### PR TITLE
Add an arity to close which includes a status code and reason

### PR DESCRIPTION
**Pull request by IGJoshua**
For one of my applications using gniazdo I need to be able to send a close code other than 1000 to the other side of the websocket connection. This PR adds that ability as an additional arity of the close function.

### CODE REVIEW

**Comment by mknoszlig** [comment]
Thanks for the patch, this looks like a useful addition to have! Would you be so kind to add a test case that asserts that the server receives the set status code and reason? for this, you would probably have to add a configurable `on-close` handler fn (analogous to [`*recv*`](https://github.com/stalefruits/gniazdo/blob/master/test/gniazdo/core_test.clj#L12)).

**Comment by IGJoshua** [comment]
@mknoszlig I've looked into the http-kit API in detail, and it appears to provide no way to determine the actual close code sent to its server, only providing an abstraction of the connection `:going-away`.

Do you have a recommendation for an alternative websocket server library that I could use that would resolve this issue? I've not had a lot of luck finding Clojure libraries for websockets that provide a lot of fine-grained control or information.

I can confirm from testing with my own application that it does in fact work as functionality that I am using downline relies on the non-1000 close code sent in order to alter the user-facing behavior of the program.

**Comment by IGJoshua** [comment]
@mknoszlig I've looked into the http-kit API in detail, and it appears to provide no way to determine the actual close code sent to its server, only providing an abstraction of the connection `:going-away`.

Do you have a recommendation for an alternative websocket server library that I could use that would resolve this issue? I've not had a lot of luck finding Clojure libraries for websockets that provide a lot of fine-grained control or information.

I can confirm from testing with my own application that it does in fact work as functionality that I am using downline relies on the non-1000 close code sent in order to alter the user-facing behavior of the program.

**Comment by mknoszlig** [comment]
@IGJoshua : thanks for giving this a try and sorry to hear this causing you trouble.

I've given the http-kit code a quick glance and it appears that the [channel implementation](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/server.clj#L201) is supposed to return a precise status (`:going-away` being one of the options).

The [channel implementation](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/AsyncChannel.java#L284) appears to map this correctly, and `:going-away` appears to not be the default.

Can you maybe provide a minimal example of what gives you the unexpected `:going-away` result regardless of actual client disconnect status code?

**Comment by IGJoshua** [comment]
I've adjusted the following in the tests in order to permit testing the value, but it always returns going-away, regardless of code sent, regardless of which method to close used.
```clojure
;; Added to be used to store the test values
(def close-code (atom nil))

;; Updated to set it to the value provided on close
(defn- ws-srv
  [req]
  (with-channel req conn
    (on-receive conn (partial *recv* req conn))
    (on-close conn #(reset! close-code %))))

;; Updated to set the close-code to nil in preparation for the test
(use-fixtures
  :each
  (fn [f]
    (reset! close-code nil)
    (let [srv (run-server ws-srv {:port 65432})]
      (try
        (f)
        (finally
          (srv))))))

;; new test
(deftest close-with-code-test
  (let [sem (java.util.concurrent.Semaphore. 0)
        conn (connect
              uri
              :on-close (fn [& _]
                          (.release sem)))]
    (is (= @close-code nil))
    (close conn)
    (with-timeout (.acquire sem))
    (is (= @close-code :going-away))))
```

**Comment by mknoszlig** [comment]
Thanks for sharing your test case - I've poked around a bit and it seems the problem lies with the call of the cleanup function before closing the connection: the default cleanup function stops the websocket client (which also closes the connection) which is why you're seeing `:going-away` as a result. If you change the implementation of `close` to

 ```clojure
(close [_ status-code reason]
           (.close session status-code reason)
           (when cleanup
             (cleanup)))
```

and run your test case again you will find that the result still isn't the expected `:invalid-payload-data` but `:unknown` instead. for some reason, `1007` isn't mapped correctly by http kit - if you use eg `1003` instead, you'll receive the expected reason kw status of `:unsupported` - so your hunch of something strange going on with the httpkit ws server was correct as well. But for our purposes i think it'll be enough to fix the bug in `close` and use a custom status that is supported. Would you be so kind to update your PR accordingly?

@jstepien @xsc : technically, the same bug exists in the vanilla `close` function - do you recall a specific reason why it was implemented in that order back in the day?

**Comment by IGJoshua** [comment]
That explains why it worked in my downline application but not in the tests. I use a custom client, so the cleanup function doesn't exist.

In any case, I've made the update and included the test.

**Comment by mknoszlig** [comment]
Thank you for your contribution!

**Comment by jstepien** [comment]
Thank you for taking the time to prepare those patches. We've released them in [1.2.0](https://clojars.org/stylefruits/gniazdo/versions/1.2.0).

**Pull request merged**
